name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install libusb-1.0-0-dev
    - name: Compiler version
      run: $CC --version
    - name: Build
      run: make

  macos:
    timeout-minutes: 1
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install pkg-config libusb
    - name: Compiler version
      run: cc --version
    - name: Build
      run: make

