name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install libusb-1.0-0-dev
    - name: Build
      run: make

  macos:
    timeout-minutes: 1
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: brew install pkg-config libusb
    - name: Build
      run: make

